#!/bin/bash

echo "Setting up gitconfig, gitexcludes and user attributes"

# use global ignore file for e.g. *.DS_Store and similar
if [ -f $HOME/.gitexcludes ]
then
  echo " - File $HOME/.gitexcludes already exists"
else
  touch $HOME/.gitexcludes
  echo "*DS_Store" >> $HOME/.gitexcludes
  echo ".idea" >> $HOME/.gitexcludes
  echo "*.swp" >> $HOME/.gitexcludes
fi

# copy gitconfig directory to $HOME/.gitconfig
cp $HOME/dev-bootstrap/git/gitconfig $HOME/.gitconfig

# set user attributes
echo "Please, enter your user name for git"
read NAME
git config --global user.name "$NAME"

echo "Please, enter your email for git"
read EMAIL
git config --global user.email "$EMAIL"

