#!/bin/bash

# install oh-my-zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# create bin folder in $HOME and prepend to $PATH
mkdir -p "$HOME/bin"
echo "export PATH=\"$HOME/bin:$PATH\"" >> "$HOME/.zprofile"

./nvim/setup
./vim/setup
./tmux/setup
./git/setup
