#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# symlink vim directory to ~/.vim
ln -nfs $DIR $HOME/.vim

# symlink vimrc configuration file to ~/.vimrc
ln -nfs $DIR/vimrc $HOME/.vimrc

# install vim plugins
mkdir -p $HOME/.vim/bundle
cd $HOME/.vim/bundle
git clone https://github.com/honza/dockerfile.vim.git
git clone https://github.com/kien/ctrlp.vim
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/Xuyuanp/nerdtree-git-plugin.git
git clone https://github.com/scrooloose/syntastic.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/airblade/vim-gitgutter.git
git clone https://github.com/bronson/vim-trailing-whitespace.git
git clone https://github.com/ervandew/supertab.git
#git clone https://github.com/fatih/vim-go
git clone https://github.com/bling/vim-airline.git
git clone https://github.com/jelera/vim-javascript-syntax.git
git clone https://github.com/kchmck/vim-coffee-script

