#!/bin/bash

# symlink vim directory to ~/.vim
ln -nfs $HOME/dev-bootstrap/vim/ ~/.vim
# symlink vimrc configuration file to ~/.vimrc
ln -nfs $HOME/dev-bootstrap/vim/vimrc ~/.vimrc
# install vim plugins
mkdir -p $HOME/.vim/bundle
cd $HOME/.vim/bundle
git clone https://github.com/honza/dockerfile.vim.git
git clone https://github.com/kien/ctrlp.vim
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/scrooloose/syntastic.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/airblade/vim-gitgutter.git
git clone https://github.com/bronson/vim-trailing-whitespace.git
git clone https://github.com/ervandew/supertab.git
#git clone https://github.com/fatih/vim-go
git clone https://github.com/bling/vim-airline.git
git clone https://github.com/jelera/vim-javascript-syntax.git

# install powerline fonts
cd $HOME
git clone https://github.com/powerline/fonts.git
./fonts/install.sh
