#!/bin/bash
curl -Lo- https://bit.ly/janus-bootstrap | bash

# disable plugins
echo "call janus#disable_plugin('unimpaired')" >> ~/.vimrc.before
echo "call janus#disable_plugin('vroom')" >> ~/.vimrc.before
echo "call janus#disable_plugin('vim-multiple-cursors')" >> ~/.vimrc.before

# set UI settings
echo 'color molokai' >> ~/.gvimrc.after
echo 'set guifont=Menlo\ Regular:h14' >> ~/.gvimrc.after

# set filetyp mapping for sql
echo '" filetype mapping' >> ~/.gvimrc.after
echo 'au BufNewFile,BufRead *.dump set filetype=sql' >> ~/.gvimrc.after
echo 'au BufNewFile,BufRead *.PRC set filetype=sql' >> ~/.gvimrc.after
echo 'au BufNewFile,BufRead *.TAB set filetype=sql' >> ~/.gvimrc.after
echo 'au BufNewFile,BufRead *.UDF set filetype=sql' >> ~/.gvimrc.after

echo '" filetype mapping' >> ~/.vimrc.after
echo 'au BufNewFile,BufRead *.dump set filetype=sql' >> ~/.vimrc.after
echo 'au BufNewFile,BufRead *.PRC set filetype=sql' >> ~/.vimrc.after
echo 'au BufNewFile,BufRead *.TAB set filetype=sql' >> ~/.vimrc.after
echo 'au BufNewFile,BufRead *.UDF set filetype=sql' >> ~/.vimrc.after

# install plugins not distributed by janus
mkdir ~/.janus
cd ~/.janus
git clone https://github.com/fatih/vim-go.git ~/.vim/bundle/vim-go
