#!/bin/bash

echo "Setting up bash prompt, default editor and aliases"

executed=`grep 'begin kgalli config' $HOME/.profile -c`
if [ "$executed" != 0 ]; then
  echo " - Skipping update of $HOME/.profile"
else
  echo " - Updating $HOME/.profile"
  read -r -d '' BASHCONFIG <<- EOM
  ## begin kgalli config
  export EDITOR=vim
  GIT_BRANCH='\$(git branch 2>/dev/null | grep '^*' | colrm 1 2)'
  HOST_NAME='\h'
  DIRECTORY='\w'
  START_GREY_COLOR='\[\e[2m\]'
  START_GREEN_COLOR='\[\e[0;32m\]'
  END_COLOR='\[\e[0m\]'
  export PS1="\$START_GREY_COLOR@\$HOST_NAME\$END_COLOR \$START_GREEN_COLOR\$DIRECTORY\$END_COLOR (\$GIT_BRANCH) "
  export EDITOR=vim

  alias ll='ls -alF'
  source ~/dev-bootstrap/git/git-completion.bash
## end kgalli config"
EOM
  echo "$BASHCONFIG" >> $HOME/.profile
fi
